# Generated by Django 6.0.3 on 2026-04-26 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano_inicio", models.DateField()),
                ("ano_termino", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("diretor", "Diretor"),
                            ("professor", "Professor"),
                            ("aluno", "Aluno"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("ficheiro", models.FileField(upload_to="materiais/")),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "ano_escolar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lemba_app.ano"
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiais",
                        to="lemba_app.disciplina",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "professor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiais",
                        to="lemba_app.perfil",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="disciplina",
            name="criado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lemba_app.perfil"
            ),
        ),
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1 Semestre"), (2, "2 Semestre")]
                    ),
                ),
                (
                    "ano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semestres",
                        to="lemba_app.ano",
                    ),
                ),
            ],
            options={
                "unique_together": {("numero", "ano")},
            },
        ),
        migrations.AddField(
            model_name="disciplina",
            name="semestre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disciplinas",
                to="lemba_app.semestre",
            ),
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=8, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turmas",
                        to="lemba_app.ano",
                    ),
                ),
                (
                    "criador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lemba_app.perfil",
                    ),
                ),
                (
                    "semestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turmas",
                        to="lemba_app.semestre",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="disciplina",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disciplinas",
                to="lemba_app.turma",
            ),
        ),
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "aluno"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lemba_app.perfil",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lemba_app.turma",
                    ),
                ),
            ],
            options={
                "unique_together": {("aluno", "turma")},
            },
        ),
    ]
